"""added seats_nb column to restaurants table

Revision ID: 6e9abf877360
Revises: a87feb54b40d
Create Date: 2022-12-21 22:45:31.911531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9abf877360'
down_revision = 'a87feb54b40d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('seats_nb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'seats_nb')
    # ### end Alembic commands ###
